version: 2.1
# Use a package of configuration called an orb.
orbs:
  # Choose either one of the orbs below
  # welcome: circleci/welcome-orb@0.4.1
  aws-cli: circleci/aws-cli@2.0.3
# Define the jobs we want to run for this project

# commands:
#   describe_created_stack:
#     steps:
#       - run: aws cloudformation describe-stacks myStack-${CIRCLE_WORKFLOW_ID:0:5} --region us-west-1

jobs:
  create_infrastructure: 
      docker:
        - image: amazon/aws-cli
      steps:
        - checkout
        - run:
            name: Create Cloudformation Stack
            command: |
              aws cloudformation deploy \
                --template-file template.yml \
                --stack-name myStack-${CIRCLE_WORKFLOW_ID:0:5} \
                --region us-west-1

  describe_created_stack:
      docker:
        - image: amazon/aws-cli
      steps:
        - checkout
        - run:
            name: describe Cloudformation Stack
            command: |
              echo $(aws cloudformation --region us-west-1 describe-stack-resources --stack-name myStack-${CIRCLE_WORKFLOW_ID:0:5} --logical-resource-id EC2Instance | jq '.StackResources .PhysicalResourceId' | xargs aws ec2 describe-instances --instance-ids)

# Sequential workflow
workflows:
  # Name the workflow
  myWorkflow:
    jobs:
      - create_infrastructure
      - describe_created_stack:
         requires:
           - create_infrastructure